# Generated by Django 5.2.7 on 2025-11-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('secondname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('regno', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
